### PR TITLE
Upgrade k8s client and controller-runtime

### PR DESCRIPTION
**Pull request by frouzbeh**

### CODE REVIEW

**Comment by frouzbeh** [comment]
Hi @amolonf, jenkins is failing for `make deps`, but locally I don't see any error. Would you take a look at it? Thanks,

**Comment by amolonf** [comment]
retest this please

**Comment by amolonf** [comment]
> Hi @amolonf, jenkins is failing for `make deps`, but locally I don't see any error. Would you take a look at it? Thanks,

It was problem with the executor. For onos-api GoLang 1.19 has been activated. This might be problem for this repository. therefore, I have activated GoLang1.19 for this repo too. Please let me know if you will face same kind of problem for other repositories too.

**Comment by frouzbeh** [comment]
> > Hi @amolonf, jenkins is failing for `make deps`, but locally I don't see any error. Would you take a look at it? Thanks,
> 
> It was problem with the executor. For onos-api GoLang 1.19 has been activated. This might be problem for this repository. therefore, I have activated GoLang1.19 for this repo too. Please let me know if you will face same kind of problem for other repositories too.

Thanks, I'll let you know if I need to upgrade golang for other repos.

**Comment by amolonf** [comment]
> > > Hi @amolonf, jenkins is failing for `make deps`, but locally I don't see any error. Would you take a look at it? Thanks,
> > 
> > 
> > It was problem with the executor. For onos-api GoLang 1.19 has been activated. This might be problem for this repository. therefore, I have activated GoLang1.19 for this repo too. Please let me know if you will face same kind of problem for other repositories too.
> 
> Thanks, I'll let you know if I need to upgrade golang for other repos.

**Review by kuujo — APPROVED** [review]

**Pull request merged**
